### ISSUE TITLE
Support Linux platform

### ISSUE THREAD

**Issue by rclement** [rclement/meeblip-controller#1]
`Meeblip Controller` does not support the Linux platform yet. As for MacOS and Windows, the Linux version should be available as a plug-in (VST2, VST3) and a standalone application.

Main changes should concern the following:
- CMake configuration
- Installer definitions
- CI scripts
- Travis-CI build and deploy
- AppVeyor build and deploy

About the installer, distribution for the various Linux distributions is still an open question. [AppImage](https://appimage.org) and [Snap](https://snapcraft.io) seem to be getting popular, user-friendly and available for all Linux distributions. Suggestions are welcome!

@johannesgunnar: feel free to jump in!

**Comment by rclement** [comment]
Quick heads-up on the `linux-support` branch:
- I manage to fix the Linux build both on my end and with Travis-CI server
- Building on Linux requires the use of Clang instead of GCC
- The standalone app version seems to be fine
- I had to disable the use of ALSA (for external MIDI device support) for the VST version not to crash at startup. Unfortunately, disabling ALSA is all or nothing, so this makes the standalone app un-usable...

What needs to be done:
- Try to fix the ALSA issue (either disable it only for VST or find another solution to avoid the segfault)
- Package the standalone application as an AppImage
- Bundle everything (standalone app, VST plugin, factory presets, etc.) with a simple installer

**Comment by rclement** [comment]
Quick note on the ALSA issue (for further reference):
- Related issue with [Dexed plugin](https://github.com/asb2m10/dexed/issues/132)
- Cherry-picking this [commit](https://github.com/WeAreROLI/JUCE/commit/32a745d9f9e10b71378b472b99c282ae9584baec#diff-61c9ed71e6156e68cc01c4c31ff9fa59) does not fix the problem, the code is still crashing when calling `snd_seq_set_client_name`

**Comment by rclement** [comment]
Linux support has been merged into `develop` branch: fa57dfb8aae533454309c532548dc445eb8c5fd5

Features:
- Standalone application as an `AppImage`
- VST plugin (tested with REAPER)
- Optional minimal installer/uninstaller putting everything into place (AppImage, VST plugin, factory presets, licenses)

Known limitations:
- The Standalone app is currently "unusable" because of the ALSA issue
- The VST plugin is usable but only in host mode (using the external MIDI device does not work because of the ALSA issue)

@johannesgunnar: you can give it a try if you want to! For now you have to build from the `develop` branch but the Linux installer will be embedded with the next release!

**Comment by probonopd** [comment]
Please provide the AppImage outside of a zip, thank you. More information: https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake
