### ISSUE TITLE
Please provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [rclement/meeblip-controller#3]
Please provide AppImage for download (not inside another archive such as a zip file). More information: https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake

**Comment by rclement** [comment]
Thanks for pointing this out. I was aware of this best-practice with the whole AppImage ecosystem but using the provided installer script was a convenient way of putting everything into place at once (factory presets, etc.).

Anyhow, the AppImage is now available to download starting with version [1.0.2](https://github.com/rclement/meeblip-controller/releases).
A deployment rule was also added to Travis-CI for direct upload of AppImage file along the rest of the artifacts (b1ae0e79d4ab51d8fa5c441d45275f2be0de50b4).

**Comment by probonopd** [comment]
Thanks. Would it be possible to name the file `Meeblip_Controller-1.0.2-x86_64.AppImage`?

**Comment by probonopd** [comment]
```
AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-9954/AppRun)
```

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems.

**Comment by rclement** [comment]
> Thanks. Would it be possible to name the file `Meeblip_Controller-1.0.2-x86_64.AppImage`?

Done

> ```
> AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /run/firejail/appimage/.appimage-9954/AppRun)
> ```
> 
> Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems.

Would building with Ubuntu Trusty (14.04 LTS) provide enough backward-compatibility?

**Comment by probonopd** [comment]
Yes.
